 version: "3" 
   services: 
    client: 
      build:
       context: ./client
       dockerfile: Dockerfile.dev
    volumes: # Links the source files to the running container 
      - ./src
     ports: - "3000:8000"